# Задание 1
* Собрать информацию о всех строящихся объектах на сайте "наш.дом.рф"
* Cохранить ее в pandas dataframe
* Cохранить pandas dataframe в excel
* Cохранить pandas dataframe в pickle
* Cохранить pandas dataframe в БД

# Задание 2
* Выберите регион
* Сравните среднюю цену квадратного метра в городах этого региона
* Определите количество строящихся объектов и квартир в регионах
* Определите объем строящегося жилья в квадратных метрах
    
# Задание 3 *
* Напишете скрипт, который сможет ежедневно собирать данные по цене, количестве и объему строящихся объектов самостоятельно и ежедневно
* Попробуйте ускорить процесс
* Добавьте возможность добавления данных в БД с указанием текущей даты.

In [60]:
import requests
import pandas as pd
import numpy as np
from tqdm.auto import tqdm

## Список объектов

In [3]:
offset_ = 2001
limit_ = 1000
url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/kn/object?offset={offset_}&limit={limit_}&sortField=devId.devShortCleanNm&sortType=asc&objStatus=0'
res = requests.get(url)
objects_data = res.json()

In [17]:
objects_data.keys()

dict_keys(['data', 'errcode'])

In [37]:
# Собрать информацию о всех строящихся объектах на сайте "наш.дом.рф"
objects_list = pd.json_normalize(objects_data.get('data').get('list'))
# objects_list.set_index('objId', inplace=True)
objects_list

,objId,rpdRegionCd,objAddr,objCommercNm,objFloorMin,objFloorMax,objElemLivingCnt,objReady100PercDt,objSquareLiving,objCompensFundFlg,...,developer.orgForm.id,developer.orgForm.fullForm,developer.orgForm.shortForm,developer.companyGroup,developer.devInn,developer.bankruptStage.bankruptStageCd,developer.bankruptStage.bankruptStageDesc,developer.bankruptStage.bankruptLawUrl,developer.orgBankruptMsgDttm,complexShortName
0,44876,72,"п Московский, ул Новая, д. 17","ЖК ""Листопад""",1,9,96,2023-03-31,4324.80,0,...,4,Общество с ограниченной ответственностью,ООО,6.021191e+09,7224011820,NaN,NaN,NaN,NaN,NaN
1,39480,29,"г Архангельск, ул Романа Куликова, блок-секция 4","Жилой комплекс""Арктический""_Жилой комплекс Арк...",11,11,26,2022-06-30,2041.63,1,...,1,Акционерное общество,АО,1.560562e+08,2902001119,NaN,NaN,NaN,NaN,NaN
2,42038,29,"г Архангельск, ул Романа Куликова, блок-секция А","Жилой комплекс""Арктический""_Жилой комплекс Арк...",11,11,56,2022-12-31,2135.80,0,...,1,Акционерное общество,АО,1.560562e+08,2902001119,NaN,NaN,NaN,NaN,NaN
3,42036,29,"г Архангельск, ул Романа Куликова, блок-секция 5","Жилой комплекс""Арктический""_Жилой комплекс Арк...",12,12,56,2023-03-31,2963.76,0,...,1,Акционерное общество,АО,1.560562e+08,2902001119,NaN,NaN,NaN,NaN,NaN
4,36633,69,"г Тверь, район Пролетарский, улица Макарова, д...",NaN,3,3,0,2022-12-31,0.00,1,...,4,Общество с ограниченной ответственностью,ООО,5.882189e+09,6905013230,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,43344,36,"г Воронеж, улица Шидловского, д. 11","Жилой квартал ""Озерки""",18,18,120,2022-09-30,6441.00,0,...,4,Общество с ограниченной ответственностью,ООО,4.252132e+09,3662276888,NaN,NaN,NaN,NaN,NaN
996,42227,25,"г Уссурийск, Александра Францева, д. 32",NaN,25,25,226,2023-09-30,11485.80,0,...,4,Общество с ограниченной ответственностью,ООО,3.040000e+02,2511106931,NaN,NaN,NaN,NaN,NaN
997,37789,36,"г Воронеж, ул Беговая, д. 59","Жилой дом ""на Беговой""",13,16,150,2022-09-30,9500.90,0,...,4,Общество с ограниченной ответственностью,ООО,NaN,3662108298,NaN,NaN,NaN,NaN,NaN
998,43991,54,"г Новосибирск, ул Аэропорт",ЖК Высота,27,27,246,2023-12-31,10330.02,0,...,4,Общество с ограниченной ответственностью,ООО,7.325886e+09,5405059643,NaN,NaN,NaN,NaN,NaN
999,40171,25,"г Уссурийск, Александра Францева, д. 32",NaN,25,25,226,2023-09-30,11485.80,0,...,4,Общество с ограниченной ответственностью,ООО,3.040000e+02,2511106931,NaN,NaN,NaN,NaN,NaN

In [42]:
obj_ID = list(objects_list['objId'])
obj_ID

[44876,
 39480,
 42038,
 42036,
 36633,
 34617,
 28916,
 24083,
 25569,
 30691,
 29664,
 34417,
 34420,
 34416,
 34419,
 34422,
 34421,
 34418,
 34423,
 27294,
 34072,
 27291,
 27292,
 27293,
 34074,
 34071,
 34075,
 27295,
 27296,
 34073,
 27681,
 26857,
 34966,
 27417,
 27415,
 27416,
 27414,
 19133,
 15686,
 28609,
 28608,
 15527,
 15528,
 15526,
 26062,
 44813,
 29713,
 29711,
 29712,
 29714,
 29271,
 12700,
 26474,
 27543,
 27544,
 18436,
 18437,
 18435,
 42688,
 29812,
 29813,
 29811,
 29814,
 45179,
 28547,
 36464,
 36463,
 8233,
 12837,
 45232,
 15663,
 15662,
 15620,
 3382,
 15664,
 3881,
 15622,
 21154,
 34547,
 41340,
 1285,
 1286,
 1284,
 23754,
 31413,
 29432,
 31106,
 34465,
 42538,
 42539,
 42537,
 25262,
 25261,
 21009,
 45734,
 44966,
 42933,
 44963,
 40357,
 42464,
 42461,
 42466,
 42468,
 15339,
 42465,
 42470,
 42469,
 15344,
 42472,
 42462,
 42463,
 15345,
 42467,
 42473,
 42471,
 42505,
 42506,
 21367,
 21361,
 21363,
 45259,
 45258,
 38736,
 38737,
 32035,
 27280,
 27284,
 27281,
 27287,
 27282,
 27285,
 27283,
 7221,
 27275,
 27286,
 27279,
 15491,
 15490,
 15489,
 3061,
 3059,
 3060,
 3062,
 3063,
 30515,
 28625,
 42839,
 45437,
 45438,
 43155,
 18100,
 39337,
 29268,
 31946,
 37957,
 37961,
 37959,
 37960,
 37953,
 37955,
 37951,
 37952,
 37954,
 2852,
 2851,
 2853,
 6569,
 34834,
 6568,
 31873,
 32006,
 8979,
 26254,
 38487,
 38926,
 38056,
 41440,
 41334,
 44479,
 44478,
 35436,
 40600,
 21875,
 21876,
 18718,
 18717,
 17817,
 17799,
 22428,
 22429,
 22424,
 22426,
 35624,
 35625,
 13972,
 28346,
 28348,
 28351,
 28344,
 28349,
 28347,
 28350,
 42226,
 44114,
 41719,
 43320,
 39056,
 44791,
 39416,
 34119,
 34120,
 35754,
 35755,
 29060,
 41134,
 26278,
 27251,
 27252,
 27240,
 27242,
 37187,
 45289,
 39171,
 39567,
 39566,
 43928,
 43931,
 43922,
 43923,
 43918,
 43915,
 43925,
 43927,
 43924,
 43926,
 43916,
 43921,
 43917,
 43919,
 43930,
 43929,
 43920,
 37966,
 43801,
 44221,
 40164,
 45354,
 39713,
 45353,
 43651,
 37971,
 36524,
 36525,
 39712,
 44218,
 39714,
 37964,
 39715,
 37972,
 37973,
 37962,
 37965,
 37963,
 40165,
 39094,
 43744,
 36269,
 39967,
 39966,
 39969,
 39968,
 44379,
 36928,
 43365,
 44378,
 44380,
 44510,
 41145,
 43364,
 43366,
 44829,
 44509,
 45824,
 44828,
 44827,
 33592,
 20676,
 39177,
 37532,
 37536,
 37535,
 37554,
 37556,
 37555,
 44452,
 44451,
 37540,
 37539,
 45159,
 45160,
 45158,
 42545,
 42596,
 29253,
 29252,
 29254,
 42198,
 42199,
 44044,
 44492,
 41424,
 28393,
 42541,
 36469,
 36470,
 31304,
 35886,
 41220,
 39330,
 38517,
 43658,
 40352,
 40353,
 45898,
 45380,
 45381,
 45378,
 45379,
 45377,
 37436,
 37433,
 37434,
 37435,
 43378,
 43116,
 43370,
 43369,
 40775,
 40774,
 40778,
 40776,
 40777,
 40779,
 43446,
 43447,
 43444,
 43445,
 44346,
 44345,
 44347,
 44349,
 44348,
 42936,
 45801,
 37916,
 41880,
 41653,
 37482,
 44340,
 44008,
 44009,
 44341,
 45508,
 40477,
 45116,
 38823,
 44657,
 45435,
 44146,
 38809,
 43090,
 43089,
 38163,
 44907,
 42343,
 42344,
 41097,
 41353,
 34707,
 34703,
 34705,
 34706,
 34708,
 34704,
 45218,
 42768,
 45181,
 4409,
 4410,
 44159,
 44158,
 42404,
 44413,
 42299,
 39104,
 37616,
 42441,
 3025,
 3018,
 3023,
 45518,
 45587,
 39984,
 45216,
 45215,
 44352,
 41258,
 42010,
 41458,
 40643,
 41459,
 39164,
 41689,
 41090,
 45627,
 43529,
 42681,
 42683,
 42682,
 42679,
 45152,
 42680,
 6250,
 6408,
 6249,
 37156,
 37793,
 37157,
 37155,
 37741,
 44627,
 41734,
 40807,
 40808,
 44842,
 41020,
 5522,
 44371,
 32159,
 39971,
 41579,
 45464,
 43113,
 45465,
 43110,
 39529,
 45319,
 40680,
 42029,
 43892,
 36675,
 30889,
 36420,
 44082,
 45342,
 44029,
 45520,
 45521,
 45519,
 7192,
 37624,
 37622,
 37623,
 11629,
 37495,
 44226,
 38836,
 38835,
 34263,
 34249,
 34264,
 34254,
 34250,
 34262,
 36245,
 37491,
 45406,
 37739,
 41194,
 45067,
 34356,
 34357,
 43100,
 45190,
 41987,
 39434,
 39436,
 43725,
 43723,
 43717,
 43722,
 43726,
 43715,
 43721,
 43719,
 43714,
 43724,
 39435,
 43716,
 43720,
 43718,
 43487,
 45512,
 29554,
 35363,
 38692,
 45268,
 36465,
 45517,
 42743,
 42744,
 42742,
 45690,
 45689,
 42544,
 42995,
 42163,
 35858,
 35857,
 35860,
 35855,
 35859,
 35856,
 39477,
 38141,
 38140,
 42053,
 42054,
 44642,
 37779,
 40698,
 38248,
 43269,
 42171,
 42172,
 44763,
 43356,
 39783,
 39781,
 39782,
 40322,
 42626,
 42456,
 38424,
 38425,
 38397,
 44594,
 42710,
 42405,
 43074,
 42431,
 42430,
 24315,
 24300,
 43865,
 43866,
 40370,
 45425,
 45431,
 45423,
 45416,
 45428,
 45426,
 45421,
 45420,
 45550,
 45427,
 45424,
 41171,
 45429,
 45430,
 45418,
 45419,
 41681,
 44231,
 41682,
 41713,
 41683,
 41712,
 44230,
 43761,
 43762,
 44595,
 43912,
 38204,
 43911,
 42728,
 40498,
 39288,
 43095,
 43096,
 45568,
 41891,
 41892,
 41894,
 41895,
 41893,
 41061,
 41064,
 41062,
 41063,
 41065,
 39998,
 44655,
 44296,
 44224,
 44091,
 44225,
 41726,
 44014,
 38128,
 38129,
 38130,
 39819,
 37984,
 41821,
 41426,
 45207,
 43669,
 43668,
 45205,
 43667,
 45206,
 40800,
 40803,
 40791,
 40796,
 40802,
 40785,
 40792,
 40797,
 40782,
 40804,
 40781,
 40793,
 40788,
 40798,
 40799,
 40787,
 40801,
 40794,
 40783,
 40784,
 40786,
 40795,
 40789,
 40790,
 40780,
 41655,
 30581,
 37919,
 41432,
 41431,
 40297,
 42375,
 42376,
 42377,
 42378,
 42379,
 42381,
 42380,
 42809,
 39082,
 41343,
 40265,
 40266,
 43798,
 43972,
 43827,
 45371,
 42362,
 45375,
 42363,
 45372,
 45370,
 45374,
 31626,
 41215,
 41216,
 41218,
 41217,
 43808,
 45210,
 45879,
 39139,
 45142,
 40256,
 40465,
 1919,
 40462,
 40460,
 40463,
 40461,
 1922,
 40464,
 38653,
 38654,
 38655,
 39224,
 44850,
 31914,
 31922,
 31936,
 31931,
 31923,
 31912,
 31937,
 31911,
 31915,
 31919,
 31935,
 31924,
 31933,
 31916,
 31932,
 31918,
 31934,
 31926,
 31921,
 31928,
 31917,
 31910,
 31920,
 31930,
 31925,
 31929,
 31927,
 31913,
 41007,
 36529,
 29611,
 33588,
 33575,
 33589,
 36531,
 27070,
 42589,
 44702,
 44701,
 45516,
 42049,
 38903,
 38902,
 43500,
 42050,
 40468,
 45149,
 41067,
 42763,
 41066,
 44668,
 44883,
 42331,
 42095,
 28871,
 42083,
 42081,
 37272,
 42082,
 28870,
 45306,
 40725,
 44882,
 44884,
 45221,
 38504,
 39970,
 43973,
 44196,
 44415,
 42909,
 45324,
 42788,
 41680,
 36266,
 44514,
 38983,
 38802,
 44140,
 41901,
 41899,
 41951,
 36437,
 36436,
 42704,
 37861,
 37858,
 37857,
 41405,
 41285,
 41265,
 42120,
 42121,
 41406,
 41410,
 41407,
 42119,
 41408,
 41409,
 44751,
 40342,
 37401,
 43379,
 36471,
 45310,
 37864,
 45621,
 38181,
 38182,
 40224,
 45162,
 31360,
 45164,
 31361,
 31999,
 45163,
 31998,
 44002,
 44003,
 42329,
 42328,
 42330,
 37880,
 45247,
 41529,
 41483,
 32186,
 37119,
 37120,
 37118,
 37121,
 42764,
 37641,
 43185,
 43184,
 37642,
 43181,
 43182,
 43183,
 37643,
 37644,
 37640,
 37639,
 37457,
 39520,
 41564,
 41666,
 44998,
 44834,
 44835,
 44833,
 32552,
 40935,
 32551,
 42631,
 42632,
 38890,
 39077,
 39467,
 43353,
 36646,
 42767,
 43805,
 42573,
 43806,
 43434,
 42536,
 45393,
 33919,
 36553,
 36554,
 39835,
 36338,
 41043,
 41132,
 33626,
 37590,
 29212,
 43646,
 43645,
 43882,
 40735,
 40734,
 40737,
 40736,
 44983,
 44385,
 44382,
 44381,
 44383,
 44384,
 38138,
 39128,
 35959,
 39129,
 39624,
 39623,
 37804,
 39622,
 45137,
 41820,
 43222,
 45511,
 38264,
 38400,
 38401,
 45298,
 42657,
 22857,
 10202,
 38930,
 42260,
 39836,
 39837,
 28974,
 40950,
 40951,
 40184,
 45196,
 45869,
 44832,
 44339,
 44826,
 39449,
 39143,
 38369,
 42874,
 42873,
 39718,
 38370,
 39717,
 34939,
 37483,
 38634,
 45345,
 35430,
 43903,
 44831,
 45382,
 44830,
 1805,
 1804,
 30504,
 1803,
 42412,
 41016,
 41017,
 41014,
 41015,
 43764,
 36227,
 37796,
 38049,
 17928,
 37703,
 37381,
 37701,
 41829,
 37704,
 37705,
 37333,
 38280,
 38281,
 30263,
 41608,
 41607,
 41609,
 43316,
 43318,
 43317,
 43315,
 44961,
 42501,
 32188,
 42500,
 44321,
 42028,
 36527,
 42483,
 44043,
 32710,
 31533,
 31489,
 31669,
 31458,
 31531,
 31528,
 41753,
 42094,
 36364,
 40933,
 44040,
 45334,
 41455,
 41660,
 43344,
 42227,
 37789,
 43991,
 40171]

# Данные по определенному объекту

In [3]:
url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/object/25002'

In [36]:
obj_description = pd.DataFrame()
description_obj_list = []
for ids in tqdm(obj_ID):
    url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/object/{ids}'
    res = requests.get(url)
    v = res.json()
    description_obj_list.append(v)
obj_description = pd.json_normalize(description_obj_list)
obj_description.tail()

  0%|          | 0/1000 [00:00<?, ?it/s]

,errcode,data.id,data.pdId,data.developer.devId,data.developer.devShortCleanNm,data.developer.devShortNm,data.developer.devFullCleanNm,data.developer.problObjCnt,data.developer.buildObjCnt,data.developer.comissObjCnt,...,data.metro.colors,data.transportDistIndex,data.transportDistIndexValue,data.greenAreaIndexValue,data.developer.bankruptStage.bankruptStageCd,data.developer.bankruptStage.bankruptStageDesc,data.developer.bankruptStage.bankruptLawUrl,data.developer.orgBankruptMsgDttm,data.airQualityIndexValue,data.complexShortNm
995,0,43344,512939,9567,СЗ ВЫБОРСТРОЙ СЕМЬ,СЗ ВЫБОРСТРОЙ СЕМЬ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ВЫБОРСТРОЙСЕМЬ,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,0,42227,472198,10204,СЗ ВЫСОТА,СЗ ВЫСОТА,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ВЫСОТА,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,0,37789,394566,10819,СЗ ВЫСОТА,СЗ ВЫСОТА,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ВЫСОТА,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,0,43991,533546,13254,СЗ ВЫСОТА,СЗ ВЫСОТА,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ВЫСОТА,0,1,0,...,[#CD0505],6 / 10,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,0,40171,460971,10204,СЗ ВЫСОТА,СЗ ВЫСОТА,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ВЫСОТА,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
# Cохранить ее в pandas dataframe
all_obj_info = pd.merge(objects_list,obj_description, left_on=['objId'], right_on=['data.id'], left_index=False, right_index=False, how='left').copy()
all_obj_info.head(5)

,objId,rpdRegionCd,objAddr,objCommercNm,objFloorMin,objFloorMax,objElemLivingCnt,objReady100PercDt,objSquareLiving,objCompensFundFlg,...,data.metro.colors,data.transportDistIndex,data.transportDistIndexValue,data.greenAreaIndexValue,data.developer.bankruptStage.bankruptStageCd,data.developer.bankruptStage.bankruptStageDesc,data.developer.bankruptStage.bankruptLawUrl,data.developer.orgBankruptMsgDttm,data.airQualityIndexValue,data.complexShortNm
0,44876,72,"п Московский, ул Новая, д. 17","ЖК ""Листопад""",1,9,96,2023-03-31,4324.80,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39480,29,"г Архангельск, ул Романа Куликова, блок-секция 4","Жилой комплекс""Арктический""_Жилой комплекс Арк...",11,11,26,2022-06-30,2041.63,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,42038,29,"г Архангельск, ул Романа Куликова, блок-секция А","Жилой комплекс""Арктический""_Жилой комплекс Арк...",11,11,56,2022-12-31,2135.80,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,42036,29,"г Архангельск, ул Романа Куликова, блок-секция 5","Жилой комплекс""Арктический""_Жилой комплекс Арк...",12,12,56,2023-03-31,2963.76,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,36633,69,"г Тверь, район Пролетарский, улица Макарова, д...",NaN,3,3,0,2022-12-31,0.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
# Cохранить pandas dataframe в excel
all_obj_info.to_excel('DMRF.xlsx', engine='xlsxwriter')

In [45]:
# Cохранить pandas dataframe в pickle
pd.to_pickle(all_obj_info, "./all_obj_info.pkl")

In [81]:
# Задание 2
# Выберите регион
all_obj_52_reg = all_obj_info[all_obj_info['rpdRegionCd'] == 52].copy()
all_obj_52_reg.head(3)

,objId,rpdRegionCd,objAddr,objCommercNm,objFloorMin,objFloorMax,objElemLivingCnt,objReady100PercDt,objSquareLiving,objCompensFundFlg,...,data.metro.colors,data.transportDistIndex,data.transportDistIndexValue,data.greenAreaIndexValue,data.developer.bankruptStage.bankruptStageCd,data.developer.bankruptStage.bankruptStageDesc,data.developer.bankruptStage.bankruptLawUrl,data.developer.orgBankruptMsgDttm,data.airQualityIndexValue,data.complexShortNm
192,35624,52,"г Нижний Новгород, ул Минина, д. 6","Жилой комплекс «Георгиевский», ЖК «Георгиевский»",2,9,29,2022-06-30,2640.25,0,...,[#D80707],9 / 10,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,35625,52,"г Нижний Новгород, наб Верхне-Волжская, д. 2а","Жилой комплекс «Георгиевский», ЖК «Георгиевский»",10,10,114,2022-06-30,12444.80,0,...,[#D80707],8 / 10,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,13972,52,"г Бор, ул Ленина, д. 58А",ЖК «Сергиевская Слобода»,7,7,150,2022-06-30,11765.88,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
all_obj_52_reg['city_name'] = all_obj_52_reg['objAddr'].str.extract(r'\bг\s*([^,]+)')
all_obj_52_reg.head(3)

,objId,rpdRegionCd,objAddr,objCommercNm,objFloorMin,objFloorMax,objElemLivingCnt,objReady100PercDt,objSquareLiving,objCompensFundFlg,...,data.transportDistIndex,data.transportDistIndexValue,data.greenAreaIndexValue,data.developer.bankruptStage.bankruptStageCd,data.developer.bankruptStage.bankruptStageDesc,data.developer.bankruptStage.bankruptLawUrl,data.developer.orgBankruptMsgDttm,data.airQualityIndexValue,data.complexShortNm,city_name
192,35624,52,"г Нижний Новгород, ул Минина, д. 6","Жилой комплекс «Георгиевский», ЖК «Георгиевский»",2,9,29,2022-06-30,2640.25,0,...,9 / 10,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нижний Новгород
193,35625,52,"г Нижний Новгород, наб Верхне-Волжская, д. 2а","Жилой комплекс «Георгиевский», ЖК «Георгиевский»",10,10,114,2022-06-30,12444.80,0,...,8 / 10,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Нижний Новгород
194,13972,52,"г Бор, ул Ленина, д. 58А",ЖК «Сергиевская Слобода»,7,7,150,2022-06-30,11765.88,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Бор

In [129]:
# Сравните среднюю цену квадратного метра в городах этого региона
comparison = pd.pivot_table(all_obj_52_reg, index=["city_name"], values=["data.objPriceAvg"],  aggfunc=[np.mean, len])
comparison

                                 mean              len
                     data.objPriceAvg data.objPriceAvg
city_name
Арзамас                  53315.000000                2
Бор                      52682.000000                1
Нижний Новгород         116556.928571               14
ород Нижний Новгород     92552.000000                1
Кстово                            NaN                1

In [137]:
# Определите количество строящихся объектов и квартир в регионах
all_obj_reg = pd.pivot_table(all_obj_info, 
                             index=['data.developer.regRegionDesc'], 
                             values=['objElemLivingCnt', 'objSquareLiving', 'objId'],  
                             aggfunc={'objElemLivingCnt': np.sum, 'objSquareLiving': np.sum, 'objId': len}, 
                             fill_value=0)
all_obj_reg.sort_values(by='objSquareLiving', ascending = False).head(30)

                              objElemLivingCnt  objId  objSquareLiving
data.developer.regRegionDesc
Москва город                             46566    101       2355062.05
Московская область                       14803     98        743979.31
Краснодарский край                       15471     56        712949.26
Санкт-Петербург город                    11604     52        536468.61
Свердловская область                      8100     42        437509.70
Новосибирская область                     6916     40        362501.63
Приморский край                           6425     33        295113.99
Ростовская область                        5112     28        256847.89
Воронежская область                       4515     26        250830.10
Владимирская область                      3662     14        211420.19
Нижегородская область                     3554     19        201571.73
Алтайский край                            3826     23        195479.92
Удмуртская Республика                     3869     19        186492.69
Ярославская область                       3667     13        175207.65
Калининградская область                   3146     29        161391.45
Самарская область                         2688     12        157305.15
Красноярский край                         2688     13        153921.05
Бурятия Республика                        2521     14        128272.62
Рязанская область                         2350      6        127237.83
Башкортостан Республика                   2524     11        124576.49
Татарстан Республика                      2160     28        122187.21
Сахалинская область                       2112     24        109170.82
Тульская область                          1910     13        100788.99
Волгоградская область                     1811     10        100479.57
Иркутская область                         1671     36         91683.41
Брянская область                          1540      8         89890.02
Архангельская область                     1750     13         80685.41
Тюменская область                         1602      9         77893.66
Крым Республика                           1666     11         75927.67
Белгородская область                      1357     19         72107.19